// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://duhparidentsufoqywam.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR1aHBhcmlkZW50c3Vmb3F5d2FtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxMzY5NTcsImV4cCI6MjA3NDcxMjk1N30.d1X9xVzWeUcaq7snMAWJRyuw0GAFwj37gn95yYji3lc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});